-- Database Schema for Inventory Management System
-- PHP 8.4 Native with MySQL

-- CREATE DATABASE IF NOT EXISTS inventory;
-- USE inventory;

-- 1. Users Table (RBAC)
CREATE TABLE IF NOT EXISTS users (
    id INT AUTO_INCREMENT PRIMARY KEY,
    username VARCHAR(50) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    role ENUM('admin', 'user') NOT NULL DEFAULT 'user',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB;

-- 2. Warehouses Table
CREATE TABLE IF NOT EXISTS warehouses (
    id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    location VARCHAR(255) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB;

-- 3. Fleets Table (Delivery Vehicles)
CREATE TABLE IF NOT EXISTS fleets (
    id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    type VARCHAR(50) NOT NULL, -- e.g. Truck, Van
    license_plate VARCHAR(20),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB;

-- 4. Items Table
CREATE TABLE IF NOT EXISTS items (
    id INT AUTO_INCREMENT PRIMARY KEY,
    code VARCHAR(50) NOT NULL UNIQUE,
    name VARCHAR(100) NOT NULL,
    unit VARCHAR(20) NOT NULL, -- e.g. Box, Pcs, Kg
    storage_temp VARCHAR(50), -- e.g. -20°C, Room Temp
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB;

-- 5. Stocks Table (Current Inventory)
CREATE TABLE IF NOT EXISTS stocks (
    warehouse_id INT NOT NULL,
    item_id INT NOT NULL,
    quantity INT NOT NULL DEFAULT 0,
    last_updated TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (warehouse_id, item_id),
    FOREIGN KEY (warehouse_id) REFERENCES warehouses(id) ON DELETE CASCADE,
    FOREIGN KEY (item_id) REFERENCES items(id) ON DELETE CASCADE
) ENGINE=InnoDB;

-- 6. Shipments Table (Transfers)
CREATE TABLE IF NOT EXISTS shipments (
    id INT AUTO_INCREMENT PRIMARY KEY,
    origin_warehouse_id INT NOT NULL,
    destination_warehouse_id INT NOT NULL,
    fleet_id INT NOT NULL,
    status ENUM('DRAFT', 'ON_DELIVERY', 'RECEIVED') NOT NULL DEFAULT 'DRAFT',
    created_by INT NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (origin_warehouse_id) REFERENCES warehouses(id),
    FOREIGN KEY (destination_warehouse_id) REFERENCES warehouses(id),
    FOREIGN KEY (fleet_id) REFERENCES fleets(id),
    FOREIGN KEY (created_by) REFERENCES users(id)
) ENGINE=InnoDB;

-- 7. Shipment Items Table
CREATE TABLE IF NOT EXISTS shipment_items (
    shipment_id INT NOT NULL,
    item_id INT NOT NULL,
    quantity INT NOT NULL,
    PRIMARY KEY (shipment_id, item_id),
    FOREIGN KEY (shipment_id) REFERENCES shipments(id) ON DELETE CASCADE,
    FOREIGN KEY (item_id) REFERENCES items(id)
) ENGINE=InnoDB;

-- 8. Stock Logs (History for Audit)
CREATE TABLE IF NOT EXISTS stock_logs (
    id INT AUTO_INCREMENT PRIMARY KEY,
    warehouse_id INT NOT NULL,
    item_id INT NOT NULL,
    quantity_change INT NOT NULL, -- positive for IN, negative for OUT
    type ENUM('IN', 'OUT', 'TRANSFER', 'ADJUSTMENT') NOT NULL,
    reason TEXT,
    reference_id INT, -- could be shipment_id or transaction_id
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (warehouse_id) REFERENCES warehouses(id),
    FOREIGN KEY (item_id) REFERENCES items(id)
) ENGINE=InnoDB;

-- Default Admin User (password: admin123)
-- Hash generated by password_hash('admin123', PASSWORD_DEFAULT)
INSERT INTO users (username, password, role) VALUES 
('admin', '$2y$12$Z9Vq7YX7B9PXmFyYhy5yKegzfx6XQpP/Y43UVElCRsudCidij9eZm', 'admin'),
('staff', '$2y$12$Z9Vq7YX7B9PXmFyYhy5yKegzfx6XQpP/Y43UVElCRsudCidij9eZm', 'user');

-- Add some Warehouses
INSERT INTO warehouses (name, location) VALUES 
('Main Hub - Jakarta', 'Jl. Gatot Subroto No. 12'),
('Cold Storage - Bandung', 'Jl. Sukajadi No. 45');

-- Add some Items
INSERT INTO items (code, name, unit, storage_temp) VALUES 
('BEV-001', 'Signature Cold Brew', 'Bottle', '2-5°C'),
('BEV-002', 'Oat Milk Latte', 'Carton', 'Room Temp'),
('SUP-99', 'Paper Cups (Large)', 'Pack', 'Dry');

-- Add some Fleets
INSERT INTO fleets (name, type, license_plate) VALUES 
('Chiller Truck 01', 'Refrigerated', 'B 9001 XYZ'),
('Van 02', 'Standard Van', 'B 4422 ABC');
